[workspace]
members = [
    "advance",
    "greeting",
    "guessing_game",
    "apollo-client-demo",
    "unit-test",
    "nom-sql",
    "concurrency",
    "oop",
    "clap_exer",
    "db_demo",
    "bytes-demo",
    "async-std-demo"
]
