mod fn_test;
mod custom_error;
mod pointer_test;
mod file_test;
mod iter_custom_test;
mod trait_test;
mod async_test;
mod vec_and_iter_test;
pub mod struct_test;
mod unsafe_test;
mod trait_test2;
mod array_test;
mod reflect;
mod generics_test;
mod generics_test2;
mod generics_test3;
mod soaring;